#!/bin/sh

audio_input=$(echo " " | dmenu -i -p "What song:")

killall mpv

# make youtube search query
query="$(printf '%s' "song audio $audio_input" | tr ' ' '+' )"

# search on invidous (youtube) instance for video id to make a url
video_id="$(curl -s "https://vid.puffyan.us/search?q=$query" | grep -Eo "watch\?v=.{11}" | head -n 1)"
youtube_url="https://youtube.com/$video_id"

# get url for bestaudio stream from the youtube video
audio_url="$(yt-dlp -f bestaudio --get-url "$youtube_url")"

# Get youtube video title for system notification
title=$(yt-dlp --get-title "$youtube_url")
notify-send "Playing: " "$title"

# add the track to mpd and play
mpv "$audio_url"

notify-send "Song Done!"
